# Tests for pdf_render_page() and the pdfium_bitmap class.
#
# shapes.pdf is generated by tools/build-fixtures.R as a 4x3 inch Cairo
# PDF with a lightblue-fill / red-stroke rectangle whose corners in plot
# coordinates are (0.5, 0.5) and (2.5, 2.5). At 72 DPI the page is
# 288x216 px and the rectangle occupies pixel rows 36..180 cols 36..180
# (Cairo flips Y relative to PDF, but the bitmap places row 1 at the
# top so the math comes out the same). Use those coordinates for
# point-sampling correctness checks.

test_that("pdf_render_page() validates dpi/annotations/rotation", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  expect_error(pdf_render_page(doc, dpi = 0),       "positive number")
  expect_error(pdf_render_page(doc, dpi = -1),      "positive number")
  expect_error(pdf_render_page(doc, dpi = NA_real_), "positive number")
  expect_error(pdf_render_page(doc, dpi = c(72, 96)), "positive number")
  expect_error(pdf_render_page(doc, dpi = "72"),    "positive number")

  expect_error(pdf_render_page(doc, annotations = NA),
               "TRUE/FALSE")
  expect_error(pdf_render_page(doc, annotations = c(TRUE, FALSE)),
               "TRUE/FALSE")
  expect_error(pdf_render_page(doc, annotations = "yes"),
               "TRUE/FALSE")

  expect_error(pdf_render_page(doc, rotation = 45),
               "one of 0, 90, 180, or 270")
  expect_error(pdf_render_page(doc, rotation = NA_integer_),
               "one of 0, 90, 180, or 270")
  expect_error(pdf_render_page(doc, rotation = c(0, 90)),
               "one of 0, 90, 180, or 270")
})

test_that("pdf_render_page() returns the documented shape", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  expect_s3_class(bmp, c("pdfium_bitmap", "nativeRaster"), exact = TRUE)
  expect_equal(dim(bmp), c(216L, 288L))      # height, width at 4x3in/72dpi
  expect_identical(attr(bmp, "channels"),    4L)
  expect_identical(attr(bmp, "dpi"),         72)
  expect_identical(attr(bmp, "source_page"), 1L)
  expect_identical(attr(bmp, "rotation_applied"), 0L)
  expect_true(is.integer(unclass(bmp)))
})

test_that("pdf_render_page() scales linearly with dpi", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp_72  <- pdf_render_page(doc, dpi = 72)
  bmp_144 <- pdf_render_page(doc, dpi = 144)
  expect_equal(dim(bmp_72),  c(216L, 288L))
  expect_equal(dim(bmp_144), c(432L, 576L))
})

test_that("pdf_render_page() rotation swaps dimensions for 90/270", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp_0   <- pdf_render_page(doc, rotation = 0)
  bmp_90  <- pdf_render_page(doc, rotation = 90)
  bmp_180 <- pdf_render_page(doc, rotation = 180)
  bmp_270 <- pdf_render_page(doc, rotation = 270)

  expect_equal(dim(bmp_0),   c(216L, 288L))
  expect_equal(dim(bmp_90),  c(288L, 216L))
  expect_equal(dim(bmp_180), c(216L, 288L))
  expect_equal(dim(bmp_270), c(288L, 216L))

  expect_identical(attr(bmp_90,  "rotation_applied"), 90L)
  expect_identical(attr(bmp_270, "rotation_applied"), 270L)
})

test_that("pdf_render_page() pixel sampling matches the fixture", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)

  # Convert the bitmap to a numeric array we can sample in RGBA space.
  arr <- as.array(bmp)

  # Sample outside the rectangle (top-left corner): Cairo paints page
  # background white.
  expect_equal(arr[5L, 5L, 1L:3L], c(1, 1, 1), tolerance = 0.02)

  # Sample inside the lightblue interior. "lightblue" = #ADD8E6 =
  # (173, 216, 230) / 255.
  cx <- 100L
  cy <- 100L
  rgb_interior <- arr[cy, cx, 1L:3L]
  expect_equal(rgb_interior[1L], 173 / 255, tolerance = 0.05)  # R
  expect_equal(rgb_interior[2L], 216 / 255, tolerance = 0.05)  # G
  expect_equal(rgb_interior[3L], 230 / 255, tolerance = 0.05)  # B

  # Alpha channel is opaque everywhere on a white-backed render.
  expect_equal(arr[, , 4L], matrix(1, nrow = 216L, ncol = 288L))
})

test_that("pdf_render_page(background = NA) skips the buffer fill", {
  # Direct unit-level check: parse_bitmap_background() is the function
  # that decides whether to fill at all. shapes.pdf paints its own
  # background so an integration test of transparency would need a
  # different fixture; the logic is what matters here.
  res_na    <- pdfium:::parse_bitmap_background(NA)
  res_white <- pdfium:::parse_bitmap_background("white")
  res_trans <- pdfium:::parse_bitmap_background("#00000000")

  expect_false(res_na$fill)
  expect_identical(res_na$argb, 0L)

  expect_true(res_white$fill)
  # ARGB: alpha=FF, red=FF, green=FF, blue=FF.
  expect_identical(res_white$argb,
                   bitwOr(bitwOr(bitwShiftL(255L, 24L), bitwShiftL(255L, 16L)),
                          bitwOr(bitwShiftL(255L, 8L), 255L)))

  # Transparent black: alpha=0, RGB=0 -> argb = 0L (still fill, the
  # fill itself uses a transparent color).
  expect_true(res_trans$fill)
  expect_identical(res_trans$argb, 0L)
})

test_that("parse_bitmap_background() rejects malformed colors", {
  expect_error(pdfium:::parse_bitmap_background(NULL),
               "color string, integer, or NA")
  expect_error(pdfium:::parse_bitmap_background(list()),
               "color string, integer, or NA")
  # col2rgb itself errors on unknown names; we surface that error.
  expect_error(pdfium:::parse_bitmap_background("not_a_color"),
               regexp = NULL)
})

test_that("as.array.pdfium_bitmap() returns RGBA doubles in 0..1", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  arr <- as.array(bmp)

  expect_type(arr, "double")
  expect_equal(dim(arr), c(216L, 288L, 4L))
  expect_true(all(arr >= 0 & arr <= 1))
})

test_that("as.raster.pdfium_bitmap() returns a hex-color raster", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  ras <- as.raster(bmp)

  expect_s3_class(ras, "raster")
  expect_type(ras, "character")
  expect_equal(dim(ras), c(216L, 288L))
  # Strip the "raster" class so element indexing returns a plain
  # character scalar, not a 1x1 raster.
  hex <- unclass(ras)
  # White outside the rectangle.
  expect_identical(hex[5L, 5L], "#FFFFFFFF")
  # Lightblue inside.
  expect_identical(toupper(hex[100L, 100L]), "#ADD8E6FF")
})

test_that("as.matrix.pdfium_bitmap() returns a plain character matrix", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  mtx <- as.matrix(bmp)

  expect_true(is.matrix(mtx))
  expect_false(inherits(mtx, "raster"))
  expect_type(mtx, "character")
  expect_equal(dim(mtx), c(216L, 288L))
})

test_that("format/print methods describe the bitmap", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  expect_match(format(bmp), "^<pdfium_bitmap 288x216 @ 72 dpi")
  expect_match(format(bmp), "page 1 of shapes\\.pdf")

  bmp_r <- pdf_render_page(doc, rotation = 90)
  expect_match(format(bmp_r), "rot 90")

  expect_output(print(bmp), "pdfium_bitmap")
})

test_that("pdf_render_page() accepts a doc, a doc + page_num, or a page", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  by_doc <- pdf_render_page(doc)
  by_doc_pn <- pdf_render_page(doc, page_num = 1L)
  page <- pdf_load_page(doc, 1L)
  on.exit(pdf_close_page(page), add = TRUE, after = FALSE)
  by_page <- pdf_render_page(page)

  # Same dimensions; the integer matrices should be bit-identical
  # because the renders are deterministic and use the same flags.
  expect_equal(dim(by_doc), dim(by_doc_pn))
  expect_equal(dim(by_doc), dim(by_page))
  expect_identical(unclass(by_doc), unclass(by_page))
})

test_that("pdf_render_page() refuses a closed page", {
  doc <- pdf_open(fixture_path("shapes"))
  page <- pdf_load_page(doc, 1L)
  pdf_close_page(page)
  expect_error(pdf_render_page(page), "Page has been closed")
  pdf_close(doc)
})

test_that("pdf_render_to_png() writes a valid PNG", {
  skip_if_not_installed("png")
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  out <- withr::local_tempfile(fileext = ".png")
  res <- pdf_render_to_png(doc, file = out, dpi = 72)
  expect_identical(res, out)
  expect_true(file.exists(out))
  expect_gt(file.size(out), 0)

  # The PNG should round-trip back to the same RGBA dimensions.
  arr <- png::readPNG(out)
  expect_equal(dim(arr), c(216L, 288L, 4L))
})

test_that("pdf_render_to_png() validates file argument", {
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  expect_error(pdf_render_to_png(doc, file = ""),
               "single non-empty character")
  expect_error(pdf_render_to_png(doc, file = NA_character_),
               "single non-empty character")
  expect_error(pdf_render_to_png(doc, file = c("a.png", "b.png")),
               "single non-empty character")
  expect_error(pdf_render_to_png(doc, file = 42),
               "single non-empty character")
})

test_that("annotations flag is plumbed through (smoke)", {
  # shapes.pdf has no annotations, so this is purely a smoke check
  # that the flag reaches PDFium without erroring. A real annotation
  # round-trip belongs in a fixture that has annots.
  doc <- pdf_open(fixture_path("shapes"))
  on.exit(pdf_close(doc), add = TRUE)

  bmp_no  <- pdf_render_page(doc, annotations = FALSE)
  bmp_yes <- pdf_render_page(doc, annotations = TRUE)
  expect_equal(dim(bmp_no), dim(bmp_yes))
})
