# Tests for pdf_render_page() and the pdfium_bitmap class.
#
# shapes.pdf is generated by tools/build-fixtures.R as a 4x3 inch Cairo
# PDF with a lightblue-fill / red-stroke rectangle whose corners in plot
# coordinates are (0.5, 0.5) and (2.5, 2.5). At 72 DPI the page is
# 288x216 px and the rectangle occupies pixel rows 36..180 cols 36..180
# (Cairo flips Y relative to PDF, but the bitmap places row 1 at the
# top so the math comes out the same). Use those coordinates for
# point-sampling correctness checks.

test_that("pdf_render_page() validates dpi/annotations/rotation", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  expect_error(pdf_render_page(doc, dpi = 0), "Assertion on")
  expect_error(pdf_render_page(doc, dpi = -1), "Assertion on")
  expect_error(pdf_render_page(doc, dpi = NA_real_), "Assertion on")
  expect_error(pdf_render_page(doc, dpi = c(72, 96)), "Assertion on")
  expect_error(pdf_render_page(doc, dpi = "72"), "Assertion on")

  expect_error(
    pdf_render_page(doc, annotations = NA),
    "Assertion on"
  )
  expect_error(
    pdf_render_page(doc, annotations = c(TRUE, FALSE)),
    "Assertion on"
  )
  expect_error(
    pdf_render_page(doc, annotations = "yes"),
    "Assertion on"
  )

  expect_error(
    pdf_render_page(doc, rotation = 45),
    "Must be element of set"
  )
  expect_error(
    pdf_render_page(doc, rotation = NA_integer_),
    "Must be element of set"
  )
  expect_error(
    pdf_render_page(doc, rotation = c(0, 90)),
    "Must be element of set"
  )
})

test_that("pdf_render_page() returns the documented shape", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  expect_s3_class(bmp, c("pdfium_bitmap", "nativeRaster"), exact = TRUE)
  expect_equal(dim(bmp), c(216L, 288L)) # height, width at 4x3in/72dpi
  expect_identical(attr(bmp, "channels"), 4L)
  expect_identical(attr(bmp, "dpi"), 72)
  expect_identical(attr(bmp, "source_page"), 1L)
  expect_identical(attr(bmp, "rotation_applied"), 0L)
  expect_true(is.integer(unclass(bmp)))
})

test_that("pdf_render_page() scales linearly with dpi", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp_72 <- pdf_render_page(doc, dpi = 72)
  bmp_144 <- pdf_render_page(doc, dpi = 144)
  expect_equal(dim(bmp_72), c(216L, 288L))
  expect_equal(dim(bmp_144), c(432L, 576L))
})

test_that("pdf_render_page() rotation swaps dimensions for 90/270", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp_0 <- pdf_render_page(doc, rotation = 0)
  bmp_90 <- pdf_render_page(doc, rotation = 90)
  bmp_180 <- pdf_render_page(doc, rotation = 180)
  bmp_270 <- pdf_render_page(doc, rotation = 270)

  expect_equal(dim(bmp_0), c(216L, 288L))
  expect_equal(dim(bmp_90), c(288L, 216L))
  expect_equal(dim(bmp_180), c(216L, 288L))
  expect_equal(dim(bmp_270), c(288L, 216L))

  expect_identical(attr(bmp_90, "rotation_applied"), 90L)
  expect_identical(attr(bmp_270, "rotation_applied"), 270L)
})

test_that("pdf_render_page() pixel sampling matches the fixture", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)

  # Convert the bitmap to a numeric array we can sample in RGBA space.
  arr <- as.array(bmp)

  # Sample outside the rectangle (top-left corner): Cairo paints page
  # background white.
  expect_equal(arr[5L, 5L, 1L:3L], c(1, 1, 1), tolerance = 0.02)

  # Sample inside the lightblue interior. "lightblue" = #ADD8E6 =
  # (173, 216, 230) / 255.
  cx <- 100L
  cy <- 100L
  rgb_interior <- arr[cy, cx, 1L:3L]
  expect_equal(rgb_interior[1L], 173 / 255, tolerance = 0.05) # R
  expect_equal(rgb_interior[2L], 216 / 255, tolerance = 0.05) # G
  expect_equal(rgb_interior[3L], 230 / 255, tolerance = 0.05) # B

  # Alpha channel is opaque everywhere on a white-backed render.
  expect_equal(arr[, , 4L], matrix(1, nrow = 216L, ncol = 288L))
})

test_that("pdf_render_page(background = NA) skips the buffer fill", {
  # Direct unit-level check: parse_bitmap_background() is the function
  # that decides whether to fill at all. shapes.pdf paints its own
  # background so an integration test of transparency would need a
  # different fixture; the logic is what matters here.
  res_na <- pdfium:::parse_bitmap_background(NA)
  res_white <- pdfium:::parse_bitmap_background("white")
  res_trans <- pdfium:::parse_bitmap_background("#00000000")

  expect_false(res_na$fill)
  expect_identical(res_na$argb, 0L)

  expect_true(res_white$fill)
  # ARGB: alpha=FF, red=FF, green=FF, blue=FF.
  expect_identical(
    res_white$argb,
    bitwOr(
      bitwOr(bitwShiftL(255L, 24L), bitwShiftL(255L, 16L)),
      bitwOr(bitwShiftL(255L, 8L), 255L)
    )
  )

  # Transparent black: alpha=0, RGB=0 -> argb = 0L (still fill, the
  # fill itself uses a transparent color).
  expect_true(res_trans$fill)
  expect_identical(res_trans$argb, 0L)
})

test_that("parse_bitmap_background() rejects malformed colors", {
  expect_error(
    pdfium:::parse_bitmap_background(NULL),
    "Assertion on"
  )
  expect_error(
    pdfium:::parse_bitmap_background(list()),
    "Assertion on"
  )
  # col2rgb itself errors on unknown names; we surface that error.
  expect_error(pdfium:::parse_bitmap_background("not_a_color"),
    regexp = NULL
  )
})

test_that("as.array.pdfium_bitmap() returns RGBA doubles in 0..1", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  arr <- as.array(bmp)

  expect_type(arr, "double")
  expect_equal(dim(arr), c(216L, 288L, 4L))
  expect_true(all(arr >= 0 & arr <= 1))
})

test_that("as.raster.pdfium_bitmap() returns a hex-color raster", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  ras <- as.raster(bmp)

  expect_s3_class(ras, "raster")
  expect_type(ras, "character")
  expect_equal(dim(ras), c(216L, 288L))
  # Strip the "raster" class so element indexing returns a plain
  # character scalar, not a 1x1 raster.
  hex <- unclass(ras)
  # White outside the rectangle.
  expect_identical(hex[5L, 5L], "#FFFFFFFF")
  # Lightblue inside.
  expect_identical(toupper(hex[100L, 100L]), "#ADD8E6FF")
})

test_that("as.matrix.pdfium_bitmap() returns a plain character matrix", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  mtx <- as.matrix(bmp)

  expect_true(is.matrix(mtx))
  expect_false(inherits(mtx, "raster"))
  expect_type(mtx, "character")
  expect_equal(dim(mtx), c(216L, 288L))
})

test_that("format/print methods describe the bitmap", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp <- pdf_render_page(doc, dpi = 72)
  expect_match(format(bmp), "^<pdfium_bitmap 288x216 @ 72 dpi")
  expect_match(format(bmp), "page 1 of shapes\\.pdf")

  bmp_r <- pdf_render_page(doc, rotation = 90)
  expect_match(format(bmp_r), "rot 90")

  expect_output(print(bmp), "pdfium_bitmap")
})

test_that("pdf_render_page() accepts a doc, a doc + page_num, or a page", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  by_doc <- pdf_render_page(doc)
  by_doc_pn <- pdf_render_page(doc, page_num = 1L)
  page <- pdf_page_load(doc, 1L)
  on.exit(pdf_page_close(page), add = TRUE, after = FALSE)
  by_page <- pdf_render_page(page)

  # Same dimensions; the integer matrices should be bit-identical
  # because the renders are deterministic and use the same flags.
  expect_equal(dim(by_doc), dim(by_doc_pn))
  expect_equal(dim(by_doc), dim(by_page))
  expect_identical(unclass(by_doc), unclass(by_page))
})

test_that("pdf_render_page() refuses a closed page", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  page <- pdf_page_load(doc, 1L)
  pdf_page_close(page)
  expect_error(pdf_render_page(page), "Page has been closed")
  pdf_doc_close(doc)
})

test_that("pdf_render_to_png() writes a valid PNG", {
  skip_if_not_installed("png")
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  out <- withr::local_tempfile(fileext = ".png")
  res <- pdf_render_to_png(doc, file = out, dpi = 72)
  expect_identical(res, out)
  expect_true(file.exists(out))
  expect_gt(file.size(out), 0)

  # The PNG should round-trip back to the same RGBA dimensions.
  arr <- png::readPNG(out)
  expect_equal(dim(arr), c(216L, 288L, 4L))
})

test_that("pdf_render_page() is a conformant nativeRaster (writePNG(bmp) == writePNG(as.array(bmp)))", {
  # Regression guard for the historical "stride-streak" render garble.
  # A pdfium_bitmap inherits from `nativeRaster`, so png::writePNG()
  # (and grid::grid.raster(), and R's graphics engine) read its
  # backing integer buffer ROW-MAJOR. If the C++ writer laid the
  # buffer out column-major (the R matrix default) those consumers
  # would shear every row sideways. The buffer must be row-major, so
  # writing the raw object and writing its as.array() decode must
  # yield byte-identical PNGs. This is the exact property whose
  # absence made downstream callers (figureextract) reshape/re-decode.
  skip_if_not_installed("png")
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)

  out_raw <- withr::local_tempfile(fileext = ".png")
  out_arr <- withr::local_tempfile(fileext = ".png")
  png::writePNG(bmp, out_raw) # raw nativeRaster path
  png::writePNG(as.array(bmp), out_arr) # positional-array path

  px_raw <- png::readPNG(out_raw)
  px_arr <- png::readPNG(out_arr)
  expect_equal(dim(px_raw), dim(px_arr))
  # Byte-for-byte identical: a column-major buffer would diverge here.
  expect_equal(px_raw, px_arr)

  # And the raw path must recover the fixture geometry: the lightblue
  # rectangle interior at [100, 100], white outside at [5, 5].
  expect_equal(px_raw[5L, 5L, 1L:3L], c(1, 1, 1), tolerance = 0.02)
  expect_equal(px_raw[100L, 100L, 1L], 173 / 255, tolerance = 0.05)
  expect_equal(px_raw[100L, 100L, 2L], 216 / 255, tolerance = 0.05)
  expect_equal(px_raw[100L, 100L, 3L], 230 / 255, tolerance = 0.05)
})

test_that("pdf_render_page_with_matrix renders at the requested size", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  m <- c(2, 0, 0, 2, 0, 0)
  bmp <- pdf_render_page_with_matrix(doc, m,
    pixel_width = 200,
    pixel_height = 150
  )
  expect_s3_class(bmp, "pdfium_bitmap")
  expect_equal(dim(bmp), c(150L, 200L))
})

test_that("pdf_render_page_with_matrix accepts clip_rect", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page_with_matrix(doc, c(1, 0, 0, 1, 0, 0),
    pixel_width = 100,
    pixel_height = 100,
    clip_rect = c(10, 10, 50, 50)
  )
  expect_s3_class(bmp, "pdfium_bitmap")
  expect_equal(dim(bmp), c(100L, 100L))
})

test_that("pdf_render_page_with_matrix validates inputs", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  expect_error(
    pdf_render_page_with_matrix(doc, c(1, 2),
      pixel_width = 100,
      pixel_height = 100
    ),
    "Assertion on"
  )
  expect_error(
    pdf_render_page_with_matrix(doc, rep(NA_real_, 6),
      pixel_width = 100,
      pixel_height = 100
    ),
    "Assertion on"
  )
  expect_error(
    pdf_render_page_with_matrix(doc, c(1, 0, 0, 1, 0, 0),
      pixel_width = 0,
      pixel_height = 100
    ),
    "Assertion on"
  )
  expect_error(
    pdf_render_page_with_matrix(doc, c(1, 0, 0, 1, 0, 0),
      pixel_width = 100,
      pixel_height = 100,
      clip_rect = c(1, 2, 3)
    ),
    "Assertion on"
  )
  # matrix() shape coercion paths.
  expect_silent({
    bmp <- pdf_render_page_with_matrix(doc,
      matrix(c(1, 0, 0, 1, 0, 0), nrow = 3, ncol = 2, byrow = TRUE),
      pixel_width = 50, pixel_height = 50
    )
    expect_s3_class(bmp, "pdfium_bitmap")
  })
  expect_error(
    pdf_render_page_with_matrix(doc, matrix(0, nrow = 4, ncol = 4),
      pixel_width = 50, pixel_height = 50
    ),
    "Assertion on"
  )
  expect_error(
    pdf_render_page_with_matrix(doc, "not numeric",
      pixel_width = 50, pixel_height = 50
    ),
    "Assertion on"
  )
  expect_error(
    pdf_render_page_with_matrix(doc, c(1, 0, 0, 1, 0, 0),
      pixel_width = c(50, 60), pixel_height = 50
    ),
    "Assertion on"
  )
})

test_that("pdf_render_to_png() validates file argument", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  expect_error(
    pdf_render_to_png(doc, file = ""),
    "Assertion on"
  )
  expect_error(
    pdf_render_to_png(doc, file = NA_character_),
    "Assertion on"
  )
  expect_error(
    pdf_render_to_png(doc, file = c("a.png", "b.png")),
    "Assertion on"
  )
  expect_error(
    pdf_render_to_png(doc, file = 42),
    "Assertion on"
  )
})

test_that("annotations flag is plumbed through (smoke)", {
  # shapes.pdf has no annotations, so this is purely a smoke check
  # that the flag reaches PDFium without erroring. A real annotation
  # round-trip belongs in a fixture that has annots.
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)

  bmp_no <- pdf_render_page(doc, annotations = FALSE)
  bmp_yes <- pdf_render_page(doc, annotations = TRUE)
  expect_equal(dim(bmp_no), dim(bmp_yes))
})

test_that("plot(bmp) draws into a PDF device without erroring", {
  # macOS arm64 only: the second `plot(bmp)` call segfaults at
  # `address 0x656c696620686375` (ASCII "uch fil…", the tail of
  # "no such file or directory") while R is lazy-loading the
  # `grid` namespace via `dyn.load()`. That signature is memory
  # corruption — a stale string buffer overwriting a function-
  # pointer slot — and the failing test is the first one in the
  # file to touch `grid::*`, not the source of the corruption.
  #
  # On Ubuntu (release/devel/oldrel) and under ASan/UBSan the test
  # passes; Apple Silicon's stricter allocator catches a write
  # that glibc and ASan slot allocators tolerate. The cross-
  # platform `pdf_render_page() output survives common downstream
  # operations` test below exercises the same C++ render +
  # as.array path without `grid`, so any regression that DOES
  # surface on Linux still has a regression check.
  #
  # TODO(humanpred/rpdfium#44): triage on macOS arm64 with lldb —
  # the trace's `dyn.load` frame is collateral, not the actual
  # crash site. Likely culprits to audit: bitmap → IntegerMatrix
  # conversion, any `Rcpp::*` SEXP that aliases PDFium-owned
  # memory without `PROTECT()`.
  skip_on_os("mac")

  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)

  out <- withr::local_tempfile(fileext = ".pdf")
  grDevices::pdf(out, width = 5, height = 4)
  expect_silent(plot(bmp))
  grDevices::dev.off()
  expect_true(file.exists(out))
  expect_gt(file.size(out), 0)

  # interpolate = FALSE path
  grDevices::pdf(out, width = 5, height = 4)
  expect_silent(plot(bmp, interpolate = FALSE))
  grDevices::dev.off()
  expect_true(file.exists(out))
})

test_that("pdf_render_page() output survives common downstream ops", {
  # Cross-platform corruption check that mirrors the work done by
  # plot.pdfium_bitmap (render -> as.array) without touching the
  # `grid` namespace. If a stray write inside cpp_render_page ever
  # leaks across an R boundary, we'd see it here as a corrupt
  # array, mismatched dim(), or use-after-free under valgrind.
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)

  arr <- as.array(bmp)
  expect_equal(dim(arr), c(dim(bmp), 4L))
  expect_true(all(is.finite(arr)))
  expect_true(all(arr >= 0 & arr <= 1))

  # Force a fresh copy through arithmetic — surfaces any aliasing
  # bug where as.array would otherwise share storage with the
  # underlying integer matrix.
  arr_copy <- arr + 0
  expect_identical(arr, arr_copy)

  # The hex-raster path also has to keep its bytes after the
  # render handle is dropped.
  ras <- as.raster(bmp)
  expect_equal(dim(ras), dim(bmp))
  expect_true(all(nchar(ras) == 9L))  # "#RRGGBBAA"
})

test_that("plot.pdfium_bitmap routes through as.array + grid::grid.raster", {
  # The pdfium_bitmap is a *conformant* nativeRaster: its C++ writer
  # fills the backing integer buffer ROW-MAJOR (see the file header of
  # src/native_raster.h and ?grDevices::as.raster, "Raster images are
  # internally represented row-first"). So the object can be handed
  # to grid::grid.raster()/png::writePNG() directly. plot() still
  # routes through `as.array(x)` -> `grid::grid.raster()` to avoid
  # rasterImage()'s 4% axis padding; this test pins that routing plus
  # the round-trip correctness of as.array().
  #
  # We verify two invariants:
  #   1. `as.array()` decodes the integer buffer correctly (row-major
  #      -> [row, col, channel]). This is the source-of-truth path
  #      that grid.raster then consumes.
  #   2. `plot.pdfium_bitmap`'s body actually uses `as.array` and
  #      `grid::grid.raster` — i.e. did not regress back to a
  #      `rasterImage` direct call.
  # End-to-end PNG byte comparison was tried first but is too
  # device-dependent (macOS Quartz vs Linux Cairo vs Windows GDI
  # disagree at the sub-pixel level even with interpolate = FALSE).
  # The two invariants above are sufficient to catch a layout
  # regression without coupling to any device backend.

  H <- 64L
  W <- 96L
  abgr <- function(r, g, b, a = 255L) {
    bitwOr(
      bitwOr(
        bitwOr(
          bitwShiftL(as.integer(a), 24L),
          bitwShiftL(as.integer(b), 16L)
        ),
        bitwShiftL(as.integer(g), 8L)
      ),
      as.integer(r)
    )
  }
  # Position-encode each pixel: R = row index, G = col index. Build a
  # *conformant* nativeRaster the way the C++ writer does: the backing
  # buffer is ROW-MAJOR, so storage index k = pixel(row = k %/% W,
  # col = k %% W). We lay the values out in that order, then attach
  # dim = c(H, W) without R re-interpreting the vector column-major.
  rows <- rep(seq_len(H), each = W) # row index, row-major order
  cols <- rep(seq_len(W), times = H) # col index, row-major order
  flat <- abgr(as.integer(rows %% 256L), as.integer(cols %% 256L), 0L)
  m <- as.integer(flat)
  dim(m) <- c(H, W) # buffer stays row-major; nativeRaster convention
  class(m) <- c("pdfium_bitmap", "nativeRaster")
  attr(m, "channels") <- 4L
  attr(m, "dpi") <- 72
  attr(m, "source_page") <- 1L
  attr(m, "source_path") <- NA_character_
  attr(m, "rotation_applied") <- 0L

  # (1) as.array() must decode each pixel to its position-encoded
  # (R = row, G = col, B = 0, A = 1) value. This is what grid.raster
  # consumes; if these values are right, grid.raster renders them
  # correctly (verified against R's documented row-major raster
  # contract).
  arr <- as.array(m)
  expect_equal(dim(arr), c(H, W, 4L))
  for (pt in list(c(3L, 5L), c(32L, 48L), c(50L, 80L))) {
    r <- pt[[1L]]
    cc <- pt[[2L]]
    expect_equal(round(arr[r, cc, 1L] * 255), r %% 256L,
      info = sprintf("R at [%d, %d]", r, cc)
    )
    expect_equal(round(arr[r, cc, 2L] * 255), cc %% 256L,
      info = sprintf("G at [%d, %d]", r, cc)
    )
    expect_equal(round(arr[r, cc, 3L] * 255), 0L,
      info = sprintf("B at [%d, %d]", r, cc)
    )
    expect_equal(round(arr[r, cc, 4L] * 255), 255L,
      info = sprintf("A at [%d, %d]", r, cc)
    )
  }

  # (2) The plot method must use the as.array + grid.raster path.
  body_src <- paste(deparse(body(plot.pdfium_bitmap)), collapse = " ")
  expect_match(body_src, "as\\.array")
  expect_match(body_src, "grid::grid\\.raster")
  expect_false(
    grepl("rasterImage", body_src),
    "plot.pdfium_bitmap must not call rasterImage directly"
  )
})

# ---- pdf_bitmap_to_page / pdf_bitmap_from_page (PdfPosConv) ----------------

test_that("pdf_bitmap_to_page / pdf_bitmap_from_page round-trip", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)
  expect_s3_class(bmp, "pdfium_bitmap")
  # At dpi = 72 pixels-per-inch equals points-per-inch, so the
  # bitmap pixel grid maps 1:1 onto PDF page-space points but the
  # y-axis is flipped (bitmap origin top-left, PDF origin bottom-
  # left). Round-trip integer pixel inputs and confirm exact
  # recovery.
  pdf_pt <- pdf_bitmap_to_page(bmp, x = c(0, 50), y = c(0, 50))
  expect_s3_class(pdf_pt, "tbl_df")
  expect_named(pdf_pt, c("x", "y"))
  expect_type(pdf_pt$x, "double")
  expect_type(pdf_pt$y, "double")
  back <- pdf_bitmap_from_page(bmp, x = pdf_pt$x, y = pdf_pt$y)
  expect_type(back$x, "integer")
  expect_type(back$y, "integer")
  expect_equal(back$x, c(0L, 50L))
  expect_equal(back$y, c(0L, 50L))
})

test_that("pdf_bitmap_to_page recycles unequal-length x and y", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)
  out <- pdf_bitmap_to_page(bmp, x = c(0, 10, 20), y = 5)
  expect_equal(nrow(out), 3L)
})

test_that("pdf_bitmap_to_page rejects bitmaps with no render-geometry", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)
  attr(bmp, "render_geometry") <- NULL
  expect_error(pdf_bitmap_to_page(bmp, 0, 0),
                 "no render-geometry metadata")
  expect_error(pdf_bitmap_from_page(bmp, 0, 0),
                 "no render-geometry metadata")
})

test_that("pdf_bitmap_to_page validates inputs", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  bmp <- pdf_render_page(doc, dpi = 72)
  expect_error(pdf_bitmap_to_page(bmp, NA, 0), "Assertion on")
  expect_error(pdf_bitmap_to_page(bmp, Inf, 0), "Assertion on")
  expect_error(pdf_bitmap_to_page("not a bitmap", 0, 0),
                 "Must inherit from class")
})

test_that("pdf_bitmap_to_page / from_page reject a closed parent doc", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  bmp <- pdf_render_page(doc, dpi = 72)
  pdf_doc_close(doc)
  expect_error(pdf_bitmap_to_page(bmp, 0, 0),
                 "Parent document has been closed")
  expect_error(pdf_bitmap_from_page(bmp, 0, 0),
                 "Parent document has been closed")
})

test_that("pdf_render_page_with_matrix bitmaps lack render-geometry", {
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  page <- pdf_page_load(doc, 1L)
  on.exit(pdf_page_close(page), add = TRUE, after = FALSE)
  bmp <- pdf_render_page_with_matrix(
    page, matrix = c(1, 0, 0, 1, 0, 0),
    pixel_width = 100L, pixel_height = 100L
  )
  expect_null(attr(bmp, "render_geometry"))
  expect_error(pdf_bitmap_to_page(bmp, 0, 0),
                 "no render-geometry metadata")
})

test_that("cpp_render_page_with_matrix rejects a wrong-length matrix", {
  # The R wrapper enforces a length-6 / 3x2 / 2x3 shape via
  # validate_matrix6; this test reaches the shim directly to cover
  # the C++ side guard.
  doc <- pdf_doc_open(fixture_path("shapes"))
  on.exit(pdf_doc_close(doc), add = TRUE)
  page <- pdf_page_load(doc, 1L)
  on.exit(pdf_page_close(page), add = TRUE, after = FALSE)
  expect_error(
    pdfium:::cpp_render_page_with_matrix(
      page$ptr, 10L, 10L, c(1, 0, 0, 1, 0),
      numeric(0), 0L, 0L, FALSE
    ),
    "length-6"
  )
})
