# Regenerate tools/pdfium-checksums.txt for the release that
# tools/pdfium-version.txt pins.
#
# Downloads every archive tools/download-pdfium.R may fetch for that
# release and records its SHA-256. tools/download-pdfium.R refuses to run
# when the checksums were recorded for another release, so run this after
# every change to tools/pdfium-version.txt (ADR-006, ADR-027). Needs
# network access and R >= 4.5.0 (tools::sha256sum()). Run it from the
# package root:
#
#   Rscript tools/update-pdfium-checksums.R

local({
  if (!exists("sha256sum", envir = asNamespace("tools"))) {
    stop("tools::sha256sum() needs R >= 4.5.0.", call. = FALSE)
  }
  release <- trimws(readLines("tools/pdfium-version.txt", warn = FALSE)[[1L]])

  # The platform tags detect_platform() in tools/download-pdfium.R can
  # return. bblanchon publishes no 32-bit macOS build, so mac-x86 is absent.
  platforms <- c(
    "linux-x64", "linux-arm64", "linux-x86",
    "linux-musl-x64", "linux-musl-arm64", "linux-musl-x86",
    "mac-x64", "mac-arm64",
    "win-x64", "win-arm64", "win-x86"
  )
  archives <- sprintf("pdfium-%s.tgz", platforms)
  base_url <- "https://github.com/bblanchon/pdfium-binaries/releases/download"

  dest_dir <- tempfile("pdfium-checksums-")
  dir.create(dest_dir)
  on.exit(unlink(dest_dir, recursive = TRUE), add = TRUE)
  dests <- file.path(dest_dir, archives)
  for (i in seq_along(archives)) {
    url <- sprintf("%s/%s/%s", base_url, release, archives[[i]])
    message("Downloading ", url)
    utils::download.file(url, dests[[i]], mode = "wb", quiet = TRUE)
  }

  writeLines(
    c(
      "# SHA-256 of each bblanchon/pdfium-binaries archive that",
      "# tools/download-pdfium.R may fetch for the pinned release. Generated by",
      "# tools/update-pdfium-checksums.R; regenerate it whenever",
      "# tools/pdfium-version.txt changes.",
      paste("release:", release),
      paste0(unname(tools::sha256sum(dests)), "  ", archives)
    ),
    "tools/pdfium-checksums.txt"
  )
  message("Wrote tools/pdfium-checksums.txt for ", release)
})
