// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_annot_count
int cpp_annot_count(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_annot_count(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_annot_count(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_annots_list
Rcpp::List cpp_annots_list(SEXP doc_ptr, SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_annots_list(SEXP doc_ptrSEXP, SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_annots_list(doc_ptr, page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_attachment_count
int cpp_attachment_count(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_attachment_count(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_attachment_count(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_attachments_list
Rcpp::List cpp_attachments_list(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_attachments_list(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_attachments_list(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_attachment_data
Rcpp::RawVector cpp_attachment_data(SEXP doc_ptr, int index_zero);
RcppExport SEXP _pdfium_cpp_attachment_data(SEXP doc_ptrSEXP, SEXP index_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type index_zero(index_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_attachment_data(doc_ptr, index_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_get_clip_path
SEXP cpp_obj_get_clip_path(SEXP obj_ptr, SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_obj_get_clip_path(SEXP obj_ptrSEXP, SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_get_clip_path(obj_ptr, page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clip_path_count_paths
int cpp_clip_path_count_paths(SEXP clip_ptr);
RcppExport SEXP _pdfium_cpp_clip_path_count_paths(SEXP clip_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type clip_ptr(clip_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_clip_path_count_paths(clip_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clip_path_count_segments
int cpp_clip_path_count_segments(SEXP clip_ptr, int path_index_zero);
RcppExport SEXP _pdfium_cpp_clip_path_count_segments(SEXP clip_ptrSEXP, SEXP path_index_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type clip_ptr(clip_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type path_index_zero(path_index_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_clip_path_count_segments(clip_ptr, path_index_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_clip_path_segments_df
Rcpp::List cpp_clip_path_segments_df(SEXP clip_ptr);
RcppExport SEXP _pdfium_cpp_clip_path_segments_df(SEXP clip_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type clip_ptr(clip_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_clip_path_segments_df(clip_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bookmarks
Rcpp::List cpp_bookmarks(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_bookmarks(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bookmarks(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_label
std::string cpp_page_label(SEXP doc_ptr, int page_index_zero);
RcppExport SEXP _pdfium_cpp_page_label(SEXP doc_ptrSEXP, SEXP page_index_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type page_index_zero(page_index_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_label(doc_ptr, page_index_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_permissions
double cpp_doc_permissions(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_permissions(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_permissions(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_file_id
Rcpp::RawVector cpp_doc_file_id(SEXP doc_ptr, int id_type);
RcppExport SEXP _pdfium_cpp_doc_file_id(SEXP doc_ptrSEXP, SEXP id_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type id_type(id_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_file_id(doc_ptr, id_type));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_page_mode
int cpp_doc_page_mode(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_page_mode(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_page_mode(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_is_tagged
bool cpp_doc_is_tagged(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_is_tagged(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_is_tagged(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_viewer_prefs
Rcpp::List cpp_doc_viewer_prefs(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_viewer_prefs(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_viewer_prefs(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_named_dests
Rcpp::List cpp_doc_named_dests(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_named_dests(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_named_dests(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_javascript
Rcpp::List cpp_doc_javascript(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_javascript(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_javascript(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_security_revision
int cpp_doc_security_revision(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_security_revision(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_security_revision(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_user_permissions
double cpp_doc_user_permissions(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_user_permissions(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_user_permissions(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_xref_valid
bool cpp_doc_xref_valid(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_xref_valid(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_xref_valid(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_trailer_ends
Rcpp::IntegerVector cpp_doc_trailer_ends(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_trailer_ends(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_trailer_ends(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_page_size_by_index
Rcpp::NumericVector cpp_doc_page_size_by_index(SEXP doc_ptr, int page_index_zero);
RcppExport SEXP _pdfium_cpp_doc_page_size_by_index(SEXP doc_ptrSEXP, SEXP page_index_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type page_index_zero(page_index_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_page_size_by_index(doc_ptr, page_index_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_meta_text
SEXP cpp_doc_meta_text(SEXP doc_ptr, std::string tag);
RcppExport SEXP _pdfium_cpp_doc_meta_text(SEXP doc_ptrSEXP, SEXP tagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type tag(tagSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_meta_text(doc_ptr, tag));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_info
Rcpp::List cpp_doc_info(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_info(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_info(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_doc_file_version
int cpp_doc_file_version(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_doc_file_version(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_doc_file_version(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_form_fields_list
Rcpp::List cpp_form_fields_list(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_form_fields_list(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_form_fields_list(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_form_object_count
int cpp_form_object_count(SEXP form_ptr);
RcppExport SEXP _pdfium_cpp_form_object_count(SEXP form_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type form_ptr(form_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_form_object_count(form_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_form_get_object
SEXP cpp_form_get_object(SEXP form_ptr, SEXP page_ptr, int index_zero_based);
RcppExport SEXP _pdfium_cpp_form_get_object(SEXP form_ptrSEXP, SEXP page_ptrSEXP, SEXP index_zero_basedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type form_ptr(form_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type index_zero_based(index_zero_basedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_form_get_object(form_ptr, page_ptr, index_zero_based));
    return rcpp_result_gen;
END_RCPP
}
// cpp_image_metadata
Rcpp::List cpp_image_metadata(SEXP obj_ptr, SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_image_metadata(SEXP obj_ptrSEXP, SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_image_metadata(obj_ptr, page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_image_pixel_size
Rcpp::IntegerVector cpp_image_pixel_size(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_image_pixel_size(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_image_pixel_size(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_image_get_bitmap
Rcpp::IntegerMatrix cpp_image_get_bitmap(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_image_get_bitmap(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_image_get_bitmap(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_image_get_rendered_bitmap
Rcpp::IntegerMatrix cpp_image_get_rendered_bitmap(SEXP doc_ptr, SEXP page_ptr, SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_image_get_rendered_bitmap(SEXP doc_ptrSEXP, SEXP page_ptrSEXP, SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_image_get_rendered_bitmap(doc_ptr, page_ptr, obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_image_data
Rcpp::RawVector cpp_image_data(SEXP obj_ptr, bool decoded);
RcppExport SEXP _pdfium_cpp_image_data(SEXP obj_ptrSEXP, SEXP decodedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    Rcpp::traits::input_parameter< bool >::type decoded(decodedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_image_data(obj_ptr, decoded));
    return rcpp_result_gen;
END_RCPP
}
// cpp_image_filters
Rcpp::CharacterVector cpp_image_filters(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_image_filters(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_image_filters(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_init_library
void cpp_init_library();
RcppExport SEXP _pdfium_cpp_init_library() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_init_library();
    return R_NilValue;
END_RCPP
}
// cpp_destroy_library
void cpp_destroy_library();
RcppExport SEXP _pdfium_cpp_destroy_library() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_destroy_library();
    return R_NilValue;
END_RCPP
}
// cpp_open_document
SEXP cpp_open_document(std::string path, std::string password);
RcppExport SEXP _pdfium_cpp_open_document(SEXP pathSEXP, SEXP passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_open_document(path, password));
    return rcpp_result_gen;
END_RCPP
}
// cpp_open_document_from_memory
SEXP cpp_open_document_from_memory(Rcpp::RawVector bytes, std::string password);
RcppExport SEXP _pdfium_cpp_open_document_from_memory(SEXP bytesSEXP, SEXP passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RawVector >::type bytes(bytesSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_open_document_from_memory(bytes, password));
    return rcpp_result_gen;
END_RCPP
}
// cpp_close_document
void cpp_close_document(SEXP ptr);
RcppExport SEXP _pdfium_cpp_close_document(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    cpp_close_document(ptr);
    return R_NilValue;
END_RCPP
}
// cpp_handle_is_valid
bool cpp_handle_is_valid(SEXP ptr);
RcppExport SEXP _pdfium_cpp_handle_is_valid(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_handle_is_valid(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_count
int cpp_page_count(SEXP ptr);
RcppExport SEXP _pdfium_cpp_page_count(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_count(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_line_cap
int cpp_obj_line_cap(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_line_cap(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_line_cap(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_line_join
int cpp_obj_line_join(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_line_join(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_line_join(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_has_transparency
bool cpp_obj_has_transparency(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_has_transparency(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_has_transparency(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_is_active
SEXP cpp_obj_is_active(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_is_active(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_is_active(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_rotated_bounds
Rcpp::NumericVector cpp_obj_rotated_bounds(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_rotated_bounds(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_rotated_bounds(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_path_draw_mode
Rcpp::List cpp_path_draw_mode(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_path_draw_mode(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_path_draw_mode(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_marks_list
Rcpp::List cpp_obj_marks_list(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_marks_list(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_marks_list(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_object_count
int cpp_page_object_count(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_object_count(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_object_count(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_get_object
SEXP cpp_page_get_object(SEXP page_ptr, int index_zero_based);
RcppExport SEXP _pdfium_cpp_page_get_object(SEXP page_ptrSEXP, SEXP index_zero_basedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type index_zero_based(index_zero_basedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_get_object(page_ptr, index_zero_based));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_type
int cpp_obj_type(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_type(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_type(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_bounds
Rcpp::NumericVector cpp_obj_bounds(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_bounds(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_bounds(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_stroke_color
Rcpp::NumericVector cpp_obj_stroke_color(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_stroke_color(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_stroke_color(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_fill_color
Rcpp::NumericVector cpp_obj_fill_color(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_fill_color(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_fill_color(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_stroke_width
double cpp_obj_stroke_width(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_stroke_width(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_stroke_width(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_matrix
Rcpp::NumericVector cpp_obj_matrix(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_matrix(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_matrix(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_dash_count
int cpp_obj_dash_count(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_dash_count(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_dash_count(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_dash_array
Rcpp::NumericVector cpp_obj_dash_array(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_dash_array(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_dash_array(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_obj_dash_phase
double cpp_obj_dash_phase(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_obj_dash_phase(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_obj_dash_phase(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_load_page
SEXP cpp_load_page(SEXP doc_ptr, int page_index_zero_based);
RcppExport SEXP _pdfium_cpp_load_page(SEXP doc_ptrSEXP, SEXP page_index_zero_basedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type page_index_zero_based(page_index_zero_basedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_load_page(doc_ptr, page_index_zero_based));
    return rcpp_result_gen;
END_RCPP
}
// cpp_close_page
void cpp_close_page(SEXP ptr);
RcppExport SEXP _pdfium_cpp_close_page(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    cpp_close_page(ptr);
    return R_NilValue;
END_RCPP
}
// cpp_page_size
Rcpp::NumericVector cpp_page_size(SEXP ptr);
RcppExport SEXP _pdfium_cpp_page_size(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_size(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_rotation
int cpp_page_rotation(SEXP ptr);
RcppExport SEXP _pdfium_cpp_page_rotation(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_rotation(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_box
Rcpp::NumericVector cpp_page_box(SEXP page_ptr, std::string box);
RcppExport SEXP _pdfium_cpp_page_box(SEXP page_ptrSEXP, SEXP boxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type box(boxSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_box(page_ptr, box));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_links
Rcpp::List cpp_page_links(SEXP doc_ptr, SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_links(SEXP doc_ptrSEXP, SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_links(doc_ptr, page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_text_chars
Rcpp::List cpp_page_text_chars(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_text_chars(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_text_chars(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_char_at_pos
int cpp_text_char_at_pos(SEXP page_ptr, double x, double y, double x_tol, double y_tol);
RcppExport SEXP _pdfium_cpp_text_char_at_pos(SEXP page_ptrSEXP, SEXP xSEXP, SEXP ySEXP, SEXP x_tolSEXP, SEXP y_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type x_tol(x_tolSEXP);
    Rcpp::traits::input_parameter< double >::type y_tol(y_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_char_at_pos(page_ptr, x, y, x_tol, y_tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_text_index_from_char
int cpp_text_text_index_from_char(SEXP page_ptr, int char_index);
RcppExport SEXP _pdfium_cpp_text_text_index_from_char(SEXP page_ptrSEXP, SEXP char_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type char_index(char_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_text_index_from_char(page_ptr, char_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_char_index_from_text
int cpp_text_char_index_from_text(SEXP page_ptr, int text_index);
RcppExport SEXP _pdfium_cpp_text_char_index_from_text(SEXP page_ptrSEXP, SEXP text_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type text_index(text_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_char_index_from_text(page_ptr, text_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_link_at_point
Rcpp::List cpp_link_at_point(SEXP doc_ptr, SEXP page_ptr, double x, double y);
RcppExport SEXP _pdfium_cpp_link_at_point(SEXP doc_ptrSEXP, SEXP page_ptrSEXP, SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_link_at_point(doc_ptr, page_ptr, x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_aactions
Rcpp::List cpp_page_aactions(SEXP doc_ptr, SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_aactions(SEXP doc_ptrSEXP, SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_aactions(doc_ptr, page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_thumbnail_raw
Rcpp::RawVector cpp_page_thumbnail_raw(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_thumbnail_raw(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_thumbnail_raw(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_thumbnail_decoded
Rcpp::RawVector cpp_page_thumbnail_decoded(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_thumbnail_decoded(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_thumbnail_decoded(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_weblinks
Rcpp::List cpp_page_weblinks(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_weblinks(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_weblinks(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_path_segment_count
int cpp_path_segment_count(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_path_segment_count(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_path_segment_count(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_path_segments
Rcpp::List cpp_path_segments(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_path_segments(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_path_segments(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_render_page
Rcpp::IntegerMatrix cpp_render_page(SEXP page_ptr, int pixel_width, int pixel_height, int rotation_code, int render_flags, int background_argb, bool fill_background);
RcppExport SEXP _pdfium_cpp_render_page(SEXP page_ptrSEXP, SEXP pixel_widthSEXP, SEXP pixel_heightSEXP, SEXP rotation_codeSEXP, SEXP render_flagsSEXP, SEXP background_argbSEXP, SEXP fill_backgroundSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type pixel_width(pixel_widthSEXP);
    Rcpp::traits::input_parameter< int >::type pixel_height(pixel_heightSEXP);
    Rcpp::traits::input_parameter< int >::type rotation_code(rotation_codeSEXP);
    Rcpp::traits::input_parameter< int >::type render_flags(render_flagsSEXP);
    Rcpp::traits::input_parameter< int >::type background_argb(background_argbSEXP);
    Rcpp::traits::input_parameter< bool >::type fill_background(fill_backgroundSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_render_page(page_ptr, pixel_width, pixel_height, rotation_code, render_flags, background_argb, fill_background));
    return rcpp_result_gen;
END_RCPP
}
// cpp_signature_count
int cpp_signature_count(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_signature_count(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_signature_count(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_signatures_list
Rcpp::List cpp_signatures_list(SEXP doc_ptr);
RcppExport SEXP _pdfium_cpp_signatures_list(SEXP doc_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_signatures_list(doc_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_signature_contents
Rcpp::RawVector cpp_signature_contents(SEXP doc_ptr, int index_zero);
RcppExport SEXP _pdfium_cpp_signature_contents(SEXP doc_ptrSEXP, SEXP index_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type index_zero(index_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_signature_contents(doc_ptr, index_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_signature_byte_range
Rcpp::IntegerMatrix cpp_signature_byte_range(SEXP doc_ptr, int index_zero);
RcppExport SEXP _pdfium_cpp_signature_byte_range(SEXP doc_ptrSEXP, SEXP index_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type index_zero(index_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_signature_byte_range(doc_ptr, index_zero));
    return rcpp_result_gen;
END_RCPP
}
// cpp_struct_tree_page
Rcpp::List cpp_struct_tree_page(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_struct_tree_page(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_struct_tree_page(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_font_size
double cpp_text_font_size(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_text_font_size(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_font_size(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_content
SEXP cpp_text_content(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_text_content(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_content(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_font
Rcpp::List cpp_text_font(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_text_font(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_font(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_text_runs
Rcpp::List cpp_page_text_runs(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_text_runs(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_text_runs(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_render_mode
int cpp_text_render_mode(SEXP obj_ptr);
RcppExport SEXP _pdfium_cpp_text_render_mode(SEXP obj_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj_ptr(obj_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_render_mode(obj_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_text_colors
Rcpp::List cpp_page_text_colors(SEXP page_ptr);
RcppExport SEXP _pdfium_cpp_page_text_colors(SEXP page_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_text_colors(page_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_text_search_page
Rcpp::List cpp_text_search_page(SEXP page_ptr, std::string query, bool match_case, bool match_whole_word, bool consecutive);
RcppExport SEXP _pdfium_cpp_text_search_page(SEXP page_ptrSEXP, SEXP querySEXP, SEXP match_caseSEXP, SEXP match_whole_wordSEXP, SEXP consecutiveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type page_ptr(page_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type query(querySEXP);
    Rcpp::traits::input_parameter< bool >::type match_case(match_caseSEXP);
    Rcpp::traits::input_parameter< bool >::type match_whole_word(match_whole_wordSEXP);
    Rcpp::traits::input_parameter< bool >::type consecutive(consecutiveSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_text_search_page(page_ptr, query, match_case, match_whole_word, consecutive));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pdfium_cpp_annot_count", (DL_FUNC) &_pdfium_cpp_annot_count, 1},
    {"_pdfium_cpp_annots_list", (DL_FUNC) &_pdfium_cpp_annots_list, 2},
    {"_pdfium_cpp_attachment_count", (DL_FUNC) &_pdfium_cpp_attachment_count, 1},
    {"_pdfium_cpp_attachments_list", (DL_FUNC) &_pdfium_cpp_attachments_list, 1},
    {"_pdfium_cpp_attachment_data", (DL_FUNC) &_pdfium_cpp_attachment_data, 2},
    {"_pdfium_cpp_obj_get_clip_path", (DL_FUNC) &_pdfium_cpp_obj_get_clip_path, 2},
    {"_pdfium_cpp_clip_path_count_paths", (DL_FUNC) &_pdfium_cpp_clip_path_count_paths, 1},
    {"_pdfium_cpp_clip_path_count_segments", (DL_FUNC) &_pdfium_cpp_clip_path_count_segments, 2},
    {"_pdfium_cpp_clip_path_segments_df", (DL_FUNC) &_pdfium_cpp_clip_path_segments_df, 1},
    {"_pdfium_cpp_bookmarks", (DL_FUNC) &_pdfium_cpp_bookmarks, 1},
    {"_pdfium_cpp_page_label", (DL_FUNC) &_pdfium_cpp_page_label, 2},
    {"_pdfium_cpp_doc_permissions", (DL_FUNC) &_pdfium_cpp_doc_permissions, 1},
    {"_pdfium_cpp_doc_file_id", (DL_FUNC) &_pdfium_cpp_doc_file_id, 2},
    {"_pdfium_cpp_doc_page_mode", (DL_FUNC) &_pdfium_cpp_doc_page_mode, 1},
    {"_pdfium_cpp_doc_is_tagged", (DL_FUNC) &_pdfium_cpp_doc_is_tagged, 1},
    {"_pdfium_cpp_doc_viewer_prefs", (DL_FUNC) &_pdfium_cpp_doc_viewer_prefs, 1},
    {"_pdfium_cpp_doc_named_dests", (DL_FUNC) &_pdfium_cpp_doc_named_dests, 1},
    {"_pdfium_cpp_doc_javascript", (DL_FUNC) &_pdfium_cpp_doc_javascript, 1},
    {"_pdfium_cpp_doc_security_revision", (DL_FUNC) &_pdfium_cpp_doc_security_revision, 1},
    {"_pdfium_cpp_doc_user_permissions", (DL_FUNC) &_pdfium_cpp_doc_user_permissions, 1},
    {"_pdfium_cpp_doc_xref_valid", (DL_FUNC) &_pdfium_cpp_doc_xref_valid, 1},
    {"_pdfium_cpp_doc_trailer_ends", (DL_FUNC) &_pdfium_cpp_doc_trailer_ends, 1},
    {"_pdfium_cpp_doc_page_size_by_index", (DL_FUNC) &_pdfium_cpp_doc_page_size_by_index, 2},
    {"_pdfium_cpp_doc_meta_text", (DL_FUNC) &_pdfium_cpp_doc_meta_text, 2},
    {"_pdfium_cpp_doc_info", (DL_FUNC) &_pdfium_cpp_doc_info, 1},
    {"_pdfium_cpp_doc_file_version", (DL_FUNC) &_pdfium_cpp_doc_file_version, 1},
    {"_pdfium_cpp_form_fields_list", (DL_FUNC) &_pdfium_cpp_form_fields_list, 1},
    {"_pdfium_cpp_form_object_count", (DL_FUNC) &_pdfium_cpp_form_object_count, 1},
    {"_pdfium_cpp_form_get_object", (DL_FUNC) &_pdfium_cpp_form_get_object, 3},
    {"_pdfium_cpp_image_metadata", (DL_FUNC) &_pdfium_cpp_image_metadata, 2},
    {"_pdfium_cpp_image_pixel_size", (DL_FUNC) &_pdfium_cpp_image_pixel_size, 1},
    {"_pdfium_cpp_image_get_bitmap", (DL_FUNC) &_pdfium_cpp_image_get_bitmap, 1},
    {"_pdfium_cpp_image_get_rendered_bitmap", (DL_FUNC) &_pdfium_cpp_image_get_rendered_bitmap, 3},
    {"_pdfium_cpp_image_data", (DL_FUNC) &_pdfium_cpp_image_data, 2},
    {"_pdfium_cpp_image_filters", (DL_FUNC) &_pdfium_cpp_image_filters, 1},
    {"_pdfium_cpp_init_library", (DL_FUNC) &_pdfium_cpp_init_library, 0},
    {"_pdfium_cpp_destroy_library", (DL_FUNC) &_pdfium_cpp_destroy_library, 0},
    {"_pdfium_cpp_open_document", (DL_FUNC) &_pdfium_cpp_open_document, 2},
    {"_pdfium_cpp_open_document_from_memory", (DL_FUNC) &_pdfium_cpp_open_document_from_memory, 2},
    {"_pdfium_cpp_close_document", (DL_FUNC) &_pdfium_cpp_close_document, 1},
    {"_pdfium_cpp_handle_is_valid", (DL_FUNC) &_pdfium_cpp_handle_is_valid, 1},
    {"_pdfium_cpp_page_count", (DL_FUNC) &_pdfium_cpp_page_count, 1},
    {"_pdfium_cpp_obj_line_cap", (DL_FUNC) &_pdfium_cpp_obj_line_cap, 1},
    {"_pdfium_cpp_obj_line_join", (DL_FUNC) &_pdfium_cpp_obj_line_join, 1},
    {"_pdfium_cpp_obj_has_transparency", (DL_FUNC) &_pdfium_cpp_obj_has_transparency, 1},
    {"_pdfium_cpp_obj_is_active", (DL_FUNC) &_pdfium_cpp_obj_is_active, 1},
    {"_pdfium_cpp_obj_rotated_bounds", (DL_FUNC) &_pdfium_cpp_obj_rotated_bounds, 1},
    {"_pdfium_cpp_path_draw_mode", (DL_FUNC) &_pdfium_cpp_path_draw_mode, 1},
    {"_pdfium_cpp_obj_marks_list", (DL_FUNC) &_pdfium_cpp_obj_marks_list, 1},
    {"_pdfium_cpp_page_object_count", (DL_FUNC) &_pdfium_cpp_page_object_count, 1},
    {"_pdfium_cpp_page_get_object", (DL_FUNC) &_pdfium_cpp_page_get_object, 2},
    {"_pdfium_cpp_obj_type", (DL_FUNC) &_pdfium_cpp_obj_type, 1},
    {"_pdfium_cpp_obj_bounds", (DL_FUNC) &_pdfium_cpp_obj_bounds, 1},
    {"_pdfium_cpp_obj_stroke_color", (DL_FUNC) &_pdfium_cpp_obj_stroke_color, 1},
    {"_pdfium_cpp_obj_fill_color", (DL_FUNC) &_pdfium_cpp_obj_fill_color, 1},
    {"_pdfium_cpp_obj_stroke_width", (DL_FUNC) &_pdfium_cpp_obj_stroke_width, 1},
    {"_pdfium_cpp_obj_matrix", (DL_FUNC) &_pdfium_cpp_obj_matrix, 1},
    {"_pdfium_cpp_obj_dash_count", (DL_FUNC) &_pdfium_cpp_obj_dash_count, 1},
    {"_pdfium_cpp_obj_dash_array", (DL_FUNC) &_pdfium_cpp_obj_dash_array, 1},
    {"_pdfium_cpp_obj_dash_phase", (DL_FUNC) &_pdfium_cpp_obj_dash_phase, 1},
    {"_pdfium_cpp_load_page", (DL_FUNC) &_pdfium_cpp_load_page, 2},
    {"_pdfium_cpp_close_page", (DL_FUNC) &_pdfium_cpp_close_page, 1},
    {"_pdfium_cpp_page_size", (DL_FUNC) &_pdfium_cpp_page_size, 1},
    {"_pdfium_cpp_page_rotation", (DL_FUNC) &_pdfium_cpp_page_rotation, 1},
    {"_pdfium_cpp_page_box", (DL_FUNC) &_pdfium_cpp_page_box, 2},
    {"_pdfium_cpp_page_links", (DL_FUNC) &_pdfium_cpp_page_links, 2},
    {"_pdfium_cpp_page_text_chars", (DL_FUNC) &_pdfium_cpp_page_text_chars, 1},
    {"_pdfium_cpp_text_char_at_pos", (DL_FUNC) &_pdfium_cpp_text_char_at_pos, 5},
    {"_pdfium_cpp_text_text_index_from_char", (DL_FUNC) &_pdfium_cpp_text_text_index_from_char, 2},
    {"_pdfium_cpp_text_char_index_from_text", (DL_FUNC) &_pdfium_cpp_text_char_index_from_text, 2},
    {"_pdfium_cpp_link_at_point", (DL_FUNC) &_pdfium_cpp_link_at_point, 4},
    {"_pdfium_cpp_page_aactions", (DL_FUNC) &_pdfium_cpp_page_aactions, 2},
    {"_pdfium_cpp_page_thumbnail_raw", (DL_FUNC) &_pdfium_cpp_page_thumbnail_raw, 1},
    {"_pdfium_cpp_page_thumbnail_decoded", (DL_FUNC) &_pdfium_cpp_page_thumbnail_decoded, 1},
    {"_pdfium_cpp_page_weblinks", (DL_FUNC) &_pdfium_cpp_page_weblinks, 1},
    {"_pdfium_cpp_path_segment_count", (DL_FUNC) &_pdfium_cpp_path_segment_count, 1},
    {"_pdfium_cpp_path_segments", (DL_FUNC) &_pdfium_cpp_path_segments, 1},
    {"_pdfium_cpp_render_page", (DL_FUNC) &_pdfium_cpp_render_page, 7},
    {"_pdfium_cpp_signature_count", (DL_FUNC) &_pdfium_cpp_signature_count, 1},
    {"_pdfium_cpp_signatures_list", (DL_FUNC) &_pdfium_cpp_signatures_list, 1},
    {"_pdfium_cpp_signature_contents", (DL_FUNC) &_pdfium_cpp_signature_contents, 2},
    {"_pdfium_cpp_signature_byte_range", (DL_FUNC) &_pdfium_cpp_signature_byte_range, 2},
    {"_pdfium_cpp_struct_tree_page", (DL_FUNC) &_pdfium_cpp_struct_tree_page, 1},
    {"_pdfium_cpp_text_font_size", (DL_FUNC) &_pdfium_cpp_text_font_size, 1},
    {"_pdfium_cpp_text_content", (DL_FUNC) &_pdfium_cpp_text_content, 1},
    {"_pdfium_cpp_text_font", (DL_FUNC) &_pdfium_cpp_text_font, 1},
    {"_pdfium_cpp_page_text_runs", (DL_FUNC) &_pdfium_cpp_page_text_runs, 1},
    {"_pdfium_cpp_text_render_mode", (DL_FUNC) &_pdfium_cpp_text_render_mode, 1},
    {"_pdfium_cpp_page_text_colors", (DL_FUNC) &_pdfium_cpp_page_text_colors, 1},
    {"_pdfium_cpp_text_search_page", (DL_FUNC) &_pdfium_cpp_text_search_page, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pdfium(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
