// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_init_library
void cpp_init_library();
RcppExport SEXP _pdfium_cpp_init_library() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_init_library();
    return R_NilValue;
END_RCPP
}
// cpp_destroy_library
void cpp_destroy_library();
RcppExport SEXP _pdfium_cpp_destroy_library() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cpp_destroy_library();
    return R_NilValue;
END_RCPP
}
// cpp_open_document
SEXP cpp_open_document(std::string path, std::string password);
RcppExport SEXP _pdfium_cpp_open_document(SEXP pathSEXP, SEXP passwordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_open_document(path, password));
    return rcpp_result_gen;
END_RCPP
}
// cpp_close_document
void cpp_close_document(SEXP ptr);
RcppExport SEXP _pdfium_cpp_close_document(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    cpp_close_document(ptr);
    return R_NilValue;
END_RCPP
}
// cpp_handle_is_valid
bool cpp_handle_is_valid(SEXP ptr);
RcppExport SEXP _pdfium_cpp_handle_is_valid(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_handle_is_valid(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_count
int cpp_page_count(SEXP ptr);
RcppExport SEXP _pdfium_cpp_page_count(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_count(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_load_page
SEXP cpp_load_page(SEXP doc_ptr, int page_index_zero_based);
RcppExport SEXP _pdfium_cpp_load_page(SEXP doc_ptrSEXP, SEXP page_index_zero_basedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type doc_ptr(doc_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type page_index_zero_based(page_index_zero_basedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_load_page(doc_ptr, page_index_zero_based));
    return rcpp_result_gen;
END_RCPP
}
// cpp_close_page
void cpp_close_page(SEXP ptr);
RcppExport SEXP _pdfium_cpp_close_page(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    cpp_close_page(ptr);
    return R_NilValue;
END_RCPP
}
// cpp_page_size
Rcpp::NumericVector cpp_page_size(SEXP ptr);
RcppExport SEXP _pdfium_cpp_page_size(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_size(ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_page_rotation
int cpp_page_rotation(SEXP ptr);
RcppExport SEXP _pdfium_cpp_page_rotation(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_page_rotation(ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pdfium_cpp_init_library", (DL_FUNC) &_pdfium_cpp_init_library, 0},
    {"_pdfium_cpp_destroy_library", (DL_FUNC) &_pdfium_cpp_destroy_library, 0},
    {"_pdfium_cpp_open_document", (DL_FUNC) &_pdfium_cpp_open_document, 2},
    {"_pdfium_cpp_close_document", (DL_FUNC) &_pdfium_cpp_close_document, 1},
    {"_pdfium_cpp_handle_is_valid", (DL_FUNC) &_pdfium_cpp_handle_is_valid, 1},
    {"_pdfium_cpp_page_count", (DL_FUNC) &_pdfium_cpp_page_count, 1},
    {"_pdfium_cpp_load_page", (DL_FUNC) &_pdfium_cpp_load_page, 2},
    {"_pdfium_cpp_close_page", (DL_FUNC) &_pdfium_cpp_close_page, 1},
    {"_pdfium_cpp_page_size", (DL_FUNC) &_pdfium_cpp_page_size, 1},
    {"_pdfium_cpp_page_rotation", (DL_FUNC) &_pdfium_cpp_page_rotation, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_pdfium(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
