# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_annot_count <- function(page_ptr) {
    .Call(`_pdfium_cpp_annot_count`, page_ptr)
}

cpp_annots_list <- function(doc_ptr, page_ptr) {
    .Call(`_pdfium_cpp_annots_list`, doc_ptr, page_ptr)
}

cpp_attachment_count <- function(doc_ptr) {
    .Call(`_pdfium_cpp_attachment_count`, doc_ptr)
}

cpp_attachments_list <- function(doc_ptr) {
    .Call(`_pdfium_cpp_attachments_list`, doc_ptr)
}

cpp_attachment_data <- function(doc_ptr, index_zero) {
    .Call(`_pdfium_cpp_attachment_data`, doc_ptr, index_zero)
}

cpp_obj_get_clip_path <- function(obj_ptr, page_ptr) {
    .Call(`_pdfium_cpp_obj_get_clip_path`, obj_ptr, page_ptr)
}

cpp_clip_path_count_paths <- function(clip_ptr) {
    .Call(`_pdfium_cpp_clip_path_count_paths`, clip_ptr)
}

cpp_clip_path_count_segments <- function(clip_ptr, path_index_zero) {
    .Call(`_pdfium_cpp_clip_path_count_segments`, clip_ptr, path_index_zero)
}

cpp_clip_path_segments_df <- function(clip_ptr) {
    .Call(`_pdfium_cpp_clip_path_segments_df`, clip_ptr)
}

cpp_bookmarks <- function(doc_ptr) {
    .Call(`_pdfium_cpp_bookmarks`, doc_ptr)
}

cpp_page_label <- function(doc_ptr, page_index_zero) {
    .Call(`_pdfium_cpp_page_label`, doc_ptr, page_index_zero)
}

cpp_doc_permissions <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_permissions`, doc_ptr)
}

cpp_doc_file_id <- function(doc_ptr, id_type) {
    .Call(`_pdfium_cpp_doc_file_id`, doc_ptr, id_type)
}

cpp_doc_page_mode <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_page_mode`, doc_ptr)
}

cpp_doc_is_tagged <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_is_tagged`, doc_ptr)
}

cpp_doc_viewer_prefs <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_viewer_prefs`, doc_ptr)
}

cpp_viewer_ref_name <- function(doc_ptr, key) {
    .Call(`_pdfium_cpp_viewer_ref_name`, doc_ptr, key)
}

cpp_doc_named_dests <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_named_dests`, doc_ptr)
}

cpp_doc_javascript <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_javascript`, doc_ptr)
}

cpp_doc_security_revision <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_security_revision`, doc_ptr)
}

cpp_doc_user_permissions <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_user_permissions`, doc_ptr)
}

cpp_doc_xref_valid <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_xref_valid`, doc_ptr)
}

cpp_doc_trailer_ends <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_trailer_ends`, doc_ptr)
}

cpp_doc_page_size_by_index <- function(doc_ptr, page_index_zero) {
    .Call(`_pdfium_cpp_doc_page_size_by_index`, doc_ptr, page_index_zero)
}

cpp_doc_meta_text <- function(doc_ptr, tag) {
    .Call(`_pdfium_cpp_doc_meta_text`, doc_ptr, tag)
}

cpp_doc_info <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_info`, doc_ptr)
}

cpp_doc_file_version <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_file_version`, doc_ptr)
}

cpp_form_fields_list <- function(doc_ptr) {
    .Call(`_pdfium_cpp_form_fields_list`, doc_ptr)
}

cpp_form_object_count <- function(form_ptr) {
    .Call(`_pdfium_cpp_form_object_count`, form_ptr)
}

cpp_form_get_object <- function(form_ptr, page_ptr, index_zero_based) {
    .Call(`_pdfium_cpp_form_get_object`, form_ptr, page_ptr, index_zero_based)
}

cpp_text_obj_glyph_path <- function(obj_ptr, glyph_code, font_size) {
    .Call(`_pdfium_cpp_text_obj_glyph_path`, obj_ptr, glyph_code, font_size)
}

cpp_text_obj_glyph_width <- function(obj_ptr, glyph_code, font_size) {
    .Call(`_pdfium_cpp_text_obj_glyph_width`, obj_ptr, glyph_code, font_size)
}

cpp_text_obj_font_metrics <- function(obj_ptr, font_size) {
    .Call(`_pdfium_cpp_text_obj_font_metrics`, obj_ptr, font_size)
}

cpp_text_char_font_info <- function(page_ptr) {
    .Call(`_pdfium_cpp_text_char_font_info`, page_ptr)
}

cpp_image_metadata <- function(obj_ptr, page_ptr) {
    .Call(`_pdfium_cpp_image_metadata`, obj_ptr, page_ptr)
}

cpp_image_pixel_size <- function(obj_ptr) {
    .Call(`_pdfium_cpp_image_pixel_size`, obj_ptr)
}

cpp_image_get_bitmap <- function(obj_ptr) {
    .Call(`_pdfium_cpp_image_get_bitmap`, obj_ptr)
}

cpp_image_get_rendered_bitmap <- function(doc_ptr, page_ptr, obj_ptr) {
    .Call(`_pdfium_cpp_image_get_rendered_bitmap`, doc_ptr, page_ptr, obj_ptr)
}

cpp_image_data <- function(obj_ptr, decoded) {
    .Call(`_pdfium_cpp_image_data`, obj_ptr, decoded)
}

cpp_image_icc_profile <- function(obj_ptr, page_ptr) {
    .Call(`_pdfium_cpp_image_icc_profile`, obj_ptr, page_ptr)
}

cpp_image_filters <- function(obj_ptr) {
    .Call(`_pdfium_cpp_image_filters`, obj_ptr)
}

cpp_init_library <- function() {
    invisible(.Call(`_pdfium_cpp_init_library`))
}

cpp_destroy_library <- function() {
    invisible(.Call(`_pdfium_cpp_destroy_library`))
}

cpp_open_document <- function(path, password) {
    .Call(`_pdfium_cpp_open_document`, path, password)
}

cpp_open_document_from_memory <- function(bytes, password) {
    .Call(`_pdfium_cpp_open_document_from_memory`, bytes, password)
}

cpp_close_document <- function(ptr) {
    invisible(.Call(`_pdfium_cpp_close_document`, ptr))
}

cpp_handle_is_valid <- function(ptr) {
    .Call(`_pdfium_cpp_handle_is_valid`, ptr)
}

cpp_page_count <- function(ptr) {
    .Call(`_pdfium_cpp_page_count`, ptr)
}

cpp_named_dest_by_name <- function(doc_ptr, name) {
    .Call(`_pdfium_cpp_named_dest_by_name`, doc_ptr, name)
}

cpp_bookmark_find <- function(doc_ptr, title_utf8) {
    .Call(`_pdfium_cpp_bookmark_find`, doc_ptr, title_utf8)
}

cpp_form_field_at_point <- function(doc_ptr, page_ptr, x, y) {
    .Call(`_pdfium_cpp_form_field_at_point`, doc_ptr, page_ptr, x, y)
}

cpp_obj_line_cap <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_line_cap`, obj_ptr)
}

cpp_obj_line_join <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_line_join`, obj_ptr)
}

cpp_obj_has_transparency <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_has_transparency`, obj_ptr)
}

cpp_obj_is_active <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_is_active`, obj_ptr)
}

cpp_obj_rotated_bounds <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_rotated_bounds`, obj_ptr)
}

cpp_path_draw_mode <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_draw_mode`, obj_ptr)
}

cpp_obj_marks_list <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_marks_list`, obj_ptr)
}

cpp_page_object_count <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_object_count`, page_ptr)
}

cpp_page_get_object <- function(page_ptr, index_zero_based) {
    .Call(`_pdfium_cpp_page_get_object`, page_ptr, index_zero_based)
}

cpp_obj_type <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_type`, obj_ptr)
}

cpp_obj_bounds <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_bounds`, obj_ptr)
}

cpp_obj_stroke_color <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_stroke_color`, obj_ptr)
}

cpp_obj_fill_color <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_fill_color`, obj_ptr)
}

cpp_obj_stroke_width <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_stroke_width`, obj_ptr)
}

cpp_obj_matrix <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_matrix`, obj_ptr)
}

cpp_obj_dash_count <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_count`, obj_ptr)
}

cpp_obj_dash_array <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_array`, obj_ptr)
}

cpp_obj_dash_phase <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_phase`, obj_ptr)
}

cpp_load_page <- function(doc_ptr, page_index_zero_based) {
    .Call(`_pdfium_cpp_load_page`, doc_ptr, page_index_zero_based)
}

cpp_close_page <- function(ptr) {
    invisible(.Call(`_pdfium_cpp_close_page`, ptr))
}

cpp_page_size <- function(ptr) {
    .Call(`_pdfium_cpp_page_size`, ptr)
}

cpp_page_rotation <- function(ptr) {
    .Call(`_pdfium_cpp_page_rotation`, ptr)
}

cpp_page_box <- function(page_ptr, box) {
    .Call(`_pdfium_cpp_page_box`, page_ptr, box)
}

cpp_page_links <- function(doc_ptr, page_ptr) {
    .Call(`_pdfium_cpp_page_links`, doc_ptr, page_ptr)
}

cpp_page_text_chars <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_text_chars`, page_ptr)
}

cpp_text_char_at_pos <- function(page_ptr, x, y, x_tol, y_tol) {
    .Call(`_pdfium_cpp_text_char_at_pos`, page_ptr, x, y, x_tol, y_tol)
}

cpp_text_text_index_from_char <- function(page_ptr, char_index) {
    .Call(`_pdfium_cpp_text_text_index_from_char`, page_ptr, char_index)
}

cpp_text_char_index_from_text <- function(page_ptr, text_index) {
    .Call(`_pdfium_cpp_text_char_index_from_text`, page_ptr, text_index)
}

cpp_link_at_point <- function(doc_ptr, page_ptr, x, y) {
    .Call(`_pdfium_cpp_link_at_point`, doc_ptr, page_ptr, x, y)
}

cpp_page_aactions <- function(doc_ptr, page_ptr) {
    .Call(`_pdfium_cpp_page_aactions`, doc_ptr, page_ptr)
}

cpp_page_thumbnail_raw <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_thumbnail_raw`, page_ptr)
}

cpp_page_thumbnail_decoded <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_thumbnail_decoded`, page_ptr)
}

cpp_page_weblinks <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_weblinks`, page_ptr)
}

cpp_path_segment_count <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_segment_count`, obj_ptr)
}

cpp_path_segments <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_segments`, obj_ptr)
}

cpp_render_page <- function(page_ptr, pixel_width, pixel_height, rotation_code, render_flags, background_argb, fill_background) {
    .Call(`_pdfium_cpp_render_page`, page_ptr, pixel_width, pixel_height, rotation_code, render_flags, background_argb, fill_background)
}

cpp_signature_count <- function(doc_ptr) {
    .Call(`_pdfium_cpp_signature_count`, doc_ptr)
}

cpp_signatures_list <- function(doc_ptr) {
    .Call(`_pdfium_cpp_signatures_list`, doc_ptr)
}

cpp_signature_contents <- function(doc_ptr, index_zero) {
    .Call(`_pdfium_cpp_signature_contents`, doc_ptr, index_zero)
}

cpp_signature_byte_range <- function(doc_ptr, index_zero) {
    .Call(`_pdfium_cpp_signature_byte_range`, doc_ptr, index_zero)
}

cpp_struct_tree_page <- function(page_ptr) {
    .Call(`_pdfium_cpp_struct_tree_page`, page_ptr)
}

cpp_text_font_size <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_font_size`, obj_ptr)
}

cpp_text_content <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_content`, obj_ptr)
}

cpp_text_font <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_font`, obj_ptr)
}

cpp_page_text_runs <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_text_runs`, page_ptr)
}

cpp_text_render_mode <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_render_mode`, obj_ptr)
}

cpp_page_text_colors <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_text_colors`, page_ptr)
}

cpp_text_search_page <- function(page_ptr, query, match_case, match_whole_word, consecutive) {
    .Call(`_pdfium_cpp_text_search_page`, page_ptr, query, match_case, match_whole_word, consecutive)
}

cpp_text_obj_rendered_bitmap <- function(doc_ptr, page_ptr, obj_ptr, scale) {
    .Call(`_pdfium_cpp_text_obj_rendered_bitmap`, doc_ptr, page_ptr, obj_ptr, scale)
}

cpp_attachment_dict_value <- function(doc_ptr, index_zero, key) {
    .Call(`_pdfium_cpp_attachment_dict_value`, doc_ptr, index_zero, key)
}

cpp_text_char_obj_index <- function(page_ptr, char_index_zero) {
    .Call(`_pdfium_cpp_text_char_obj_index`, page_ptr, char_index_zero)
}

