# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_obj_get_clip_path <- function(obj_ptr, page_ptr) {
    .Call(`_pdfium_cpp_obj_get_clip_path`, obj_ptr, page_ptr)
}

cpp_clip_path_count_paths <- function(clip_ptr) {
    .Call(`_pdfium_cpp_clip_path_count_paths`, clip_ptr)
}

cpp_clip_path_count_segments <- function(clip_ptr, path_index_zero) {
    .Call(`_pdfium_cpp_clip_path_count_segments`, clip_ptr, path_index_zero)
}

cpp_clip_path_segments_df <- function(clip_ptr) {
    .Call(`_pdfium_cpp_clip_path_segments_df`, clip_ptr)
}

cpp_doc_file_id <- function(doc_ptr, id_type) {
    .Call(`_pdfium_cpp_doc_file_id`, doc_ptr, id_type)
}

cpp_doc_page_mode <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_page_mode`, doc_ptr)
}

cpp_doc_meta_text <- function(doc_ptr, tag) {
    .Call(`_pdfium_cpp_doc_meta_text`, doc_ptr, tag)
}

cpp_doc_info <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_info`, doc_ptr)
}

cpp_doc_file_version <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_file_version`, doc_ptr)
}

cpp_form_object_count <- function(form_ptr) {
    .Call(`_pdfium_cpp_form_object_count`, form_ptr)
}

cpp_form_get_object <- function(form_ptr, page_ptr, index_zero_based) {
    .Call(`_pdfium_cpp_form_get_object`, form_ptr, page_ptr, index_zero_based)
}

cpp_image_metadata <- function(obj_ptr, page_ptr) {
    .Call(`_pdfium_cpp_image_metadata`, obj_ptr, page_ptr)
}

cpp_image_pixel_size <- function(obj_ptr) {
    .Call(`_pdfium_cpp_image_pixel_size`, obj_ptr)
}

cpp_image_get_bitmap <- function(obj_ptr) {
    .Call(`_pdfium_cpp_image_get_bitmap`, obj_ptr)
}

cpp_image_get_rendered_bitmap <- function(doc_ptr, page_ptr, obj_ptr) {
    .Call(`_pdfium_cpp_image_get_rendered_bitmap`, doc_ptr, page_ptr, obj_ptr)
}

cpp_image_data <- function(obj_ptr, decoded) {
    .Call(`_pdfium_cpp_image_data`, obj_ptr, decoded)
}

cpp_image_filters <- function(obj_ptr) {
    .Call(`_pdfium_cpp_image_filters`, obj_ptr)
}

cpp_init_library <- function() {
    invisible(.Call(`_pdfium_cpp_init_library`))
}

cpp_destroy_library <- function() {
    invisible(.Call(`_pdfium_cpp_destroy_library`))
}

cpp_open_document <- function(path, password) {
    .Call(`_pdfium_cpp_open_document`, path, password)
}

cpp_open_document_from_memory <- function(bytes, password) {
    .Call(`_pdfium_cpp_open_document_from_memory`, bytes, password)
}

cpp_close_document <- function(ptr) {
    invisible(.Call(`_pdfium_cpp_close_document`, ptr))
}

cpp_handle_is_valid <- function(ptr) {
    .Call(`_pdfium_cpp_handle_is_valid`, ptr)
}

cpp_page_count <- function(ptr) {
    .Call(`_pdfium_cpp_page_count`, ptr)
}

cpp_page_object_count <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_object_count`, page_ptr)
}

cpp_page_get_object <- function(page_ptr, index_zero_based) {
    .Call(`_pdfium_cpp_page_get_object`, page_ptr, index_zero_based)
}

cpp_obj_type <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_type`, obj_ptr)
}

cpp_obj_bounds <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_bounds`, obj_ptr)
}

cpp_obj_stroke_color <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_stroke_color`, obj_ptr)
}

cpp_obj_fill_color <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_fill_color`, obj_ptr)
}

cpp_obj_stroke_width <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_stroke_width`, obj_ptr)
}

cpp_obj_matrix <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_matrix`, obj_ptr)
}

cpp_obj_dash_count <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_count`, obj_ptr)
}

cpp_obj_dash_array <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_array`, obj_ptr)
}

cpp_obj_dash_phase <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_phase`, obj_ptr)
}

cpp_load_page <- function(doc_ptr, page_index_zero_based) {
    .Call(`_pdfium_cpp_load_page`, doc_ptr, page_index_zero_based)
}

cpp_close_page <- function(ptr) {
    invisible(.Call(`_pdfium_cpp_close_page`, ptr))
}

cpp_page_size <- function(ptr) {
    .Call(`_pdfium_cpp_page_size`, ptr)
}

cpp_page_rotation <- function(ptr) {
    .Call(`_pdfium_cpp_page_rotation`, ptr)
}

cpp_page_box <- function(page_ptr, box) {
    .Call(`_pdfium_cpp_page_box`, page_ptr, box)
}

cpp_page_links <- function(doc_ptr, page_ptr) {
    .Call(`_pdfium_cpp_page_links`, doc_ptr, page_ptr)
}

cpp_page_text_chars <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_text_chars`, page_ptr)
}

cpp_path_segment_count <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_segment_count`, obj_ptr)
}

cpp_path_segments <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_segments`, obj_ptr)
}

cpp_render_page <- function(page_ptr, pixel_width, pixel_height, rotation_code, render_flags, background_argb, fill_background) {
    .Call(`_pdfium_cpp_render_page`, page_ptr, pixel_width, pixel_height, rotation_code, render_flags, background_argb, fill_background)
}

cpp_text_font_size <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_font_size`, obj_ptr)
}

cpp_text_content <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_content`, obj_ptr)
}

cpp_text_font <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_font`, obj_ptr)
}

cpp_page_text_runs <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_text_runs`, page_ptr)
}

