# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_doc_meta_text <- function(doc_ptr, tag) {
    .Call(`_pdfium_cpp_doc_meta_text`, doc_ptr, tag)
}

cpp_doc_info <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_info`, doc_ptr)
}

cpp_doc_file_version <- function(doc_ptr) {
    .Call(`_pdfium_cpp_doc_file_version`, doc_ptr)
}

cpp_init_library <- function() {
    invisible(.Call(`_pdfium_cpp_init_library`))
}

cpp_destroy_library <- function() {
    invisible(.Call(`_pdfium_cpp_destroy_library`))
}

cpp_open_document <- function(path, password) {
    .Call(`_pdfium_cpp_open_document`, path, password)
}

cpp_close_document <- function(ptr) {
    invisible(.Call(`_pdfium_cpp_close_document`, ptr))
}

cpp_handle_is_valid <- function(ptr) {
    .Call(`_pdfium_cpp_handle_is_valid`, ptr)
}

cpp_page_count <- function(ptr) {
    .Call(`_pdfium_cpp_page_count`, ptr)
}

cpp_page_object_count <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_object_count`, page_ptr)
}

cpp_page_get_object <- function(page_ptr, index_zero_based) {
    .Call(`_pdfium_cpp_page_get_object`, page_ptr, index_zero_based)
}

cpp_obj_type <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_type`, obj_ptr)
}

cpp_obj_bounds <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_bounds`, obj_ptr)
}

cpp_obj_stroke_color <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_stroke_color`, obj_ptr)
}

cpp_obj_fill_color <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_fill_color`, obj_ptr)
}

cpp_obj_stroke_width <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_stroke_width`, obj_ptr)
}

cpp_obj_matrix <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_matrix`, obj_ptr)
}

cpp_obj_dash_count <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_count`, obj_ptr)
}

cpp_obj_dash_array <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_array`, obj_ptr)
}

cpp_obj_dash_phase <- function(obj_ptr) {
    .Call(`_pdfium_cpp_obj_dash_phase`, obj_ptr)
}

cpp_load_page <- function(doc_ptr, page_index_zero_based) {
    .Call(`_pdfium_cpp_load_page`, doc_ptr, page_index_zero_based)
}

cpp_close_page <- function(ptr) {
    invisible(.Call(`_pdfium_cpp_close_page`, ptr))
}

cpp_page_size <- function(ptr) {
    .Call(`_pdfium_cpp_page_size`, ptr)
}

cpp_page_rotation <- function(ptr) {
    .Call(`_pdfium_cpp_page_rotation`, ptr)
}

cpp_path_segment_count <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_segment_count`, obj_ptr)
}

cpp_path_segments <- function(obj_ptr) {
    .Call(`_pdfium_cpp_path_segments`, obj_ptr)
}

cpp_text_font_size <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_font_size`, obj_ptr)
}

cpp_text_content <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_content`, obj_ptr)
}

cpp_text_font <- function(obj_ptr) {
    .Call(`_pdfium_cpp_text_font`, obj_ptr)
}

cpp_page_text_runs <- function(page_ptr) {
    .Call(`_pdfium_cpp_page_text_runs`, page_ptr)
}

